<h3 style="text-align:center"></h3>
<br>
<h2> Background </h2>
<p> The AHI sensor on board Himawari-8 and Himawari-9 closely resembles the ABI on the GOES-R series. In an initiative to expand the spatial coverage of our Land Surface Temperature (LST) product, we applied the enterprise retrieval algorithm to the AHI sensor. The team initiated the production of Himawari-8 LST from Nov. 23, 2021, until Dec. 12, 2022, when its data ceased. This endeavor has been succeeded by the Near-Real-Time (NRT) generation of Himawari-9 since Nov. 5, 2022. Currently, Himawari LST is output with a latency of less than one day at an hourly frequency. It's important to note that all related results are considered experimental and intended for evaluation purposes only at the current stage. </p>
