<!--<div id="skipNav"><a href="#skipTarget">Skip Top Navigation</a></div>-->
<div class="clearing"></div>
<div class="bannerContainer">
	<div id="printBanner">
		<img src="images/banner/NewPrintBanner.jpg" 
		alt="only rendered in printing; banner identifies NOAA, NESDIS, and STAR organizations" /></div>
	<div id="screenBanner">
		<div class="left">
   		<a href="http://www.star.nesdis.noaa.gov/star/index.php" title="link to STAR home page"><img 
			src="images/banner/StarBanner.png" 
   		alt="STAR title banner" width="570" height="79" /></a></div>
   		<div class="right">
   		<a href="http://www.nesdis.noaa.gov/" title="link to NESDIS home page"><img 
 			src="images/banner/NOAA50th_logo-1.png" 
 			alt="NESDIS Logo" 
 			width="280" height="79" /></a></div>
 	</div>
 	<div class="clearing"> </div>
</div>
