<h3 style="text-align:center">Team Members: Yunyue Yu, Corinne Carter, and Zhangyan Jiang</h3>
<br>
<h2> Background </h2>

<p> Green Vegetation Fraction (GVF) corresponds to the fraction of ground covered by green vegetation; it quantifies the
spatial extent of the vegetation. GVF is a very good candidate for the replacement of classical vegetation indices for
the monitoring of ecosystems. It is needed for land surface initialization in numerical weather prediction models and
land surface monitoring as well. </p>
<br>
<h2> Data access </h2>

<p> The data are available to the public via NOAA <a href="https://www.avl.class.noaa.gov/saa/products/search?sub_id=0&datatype_family=JPSS_NGRN&submit.x=28&submit.y=8" target="_blank">CLASS</a>, and please refer to the <a href="others/documents/instructions_vi_gvf_dat_from_CLASS.pdf" target="_blank">instruction</a> for details on how to order and download the data . </p>
<br>
