<div class="searchBox">
   <form method="get" action="http://usasearch.gov/search">
      <input type="hidden" name="affiliate" value="orbit.nesdis.noaa.gov_star">
      <input type="hidden" name="v:project" value="firstgov">
      <input value="Enter search term(s)" onfocus="if(this.value=='Enter search term(s)')this.value='';" type="text" name="query" id="query-field">
      <input type="submit" value="Go" title="execute search" id="Go" />
      <br />
      <input type="radio" id="STAR" name="affiliate" checked="checked" value="orbit.nesdis.noaa.gov_star">
      <label for="STAR">This site only</label>&nbsp;
      <input type="radio" id="NOAA" name="affiliate" value="noaa.gov">
      <label for="NOAA">All of NOAA</label>
      <p><a href="http://usasearch.gov/search?v:project=firstgov&amp;form=advanced-firstgov&amp;v:frame=form&amp;affiliate=orbit.nesdis.noaa.gov_star">Advanced Search</a></p>
   </form>
</div>
<div class="leftNav"><!--<div id="leftNav">-->
   <ul>
      <li id="index"><a href="index.php">Land Product Development Team</a>
         <ul class="detailContainer">
            <li id="Events"><a href="events.php">Events</a></li>
         </ul>
      </li>
   </ul>
   <ul>
      <li id="LST"><a href="index.php?product=LST">Land Surface Temperature</a>
         <ul class="detailContainer">
            <li id="GOES-East LST"><a href="index.php?sat=GOESR&product=LST">GOES-East ABI LST</a>
               <ul class="detailContainer">
                  <li id="GOES-East LST daily animation"><a href="animation.php?sat=GOESR&mode=2KMFD&product=LST">FD LST (2 km) daily Animations</a></li>
                  <li id="GOES-East LST validation"><a href="validation.php?sat=GOESR&sensor=ABI&mode=2KMFD&product=LST">FD LST (2 km) Validation</a></li>
                  <li id="GOES-East LST daily animation"><a href="animation.php?sat=GOESR&mode=FD&product=LST">FD LST (10 km) daily Animations</a></li>
                  <li id="GOES-East LST validation"><a href="validation.php?sat=GOESR&sensor=ABI&mode=FD&product=LST">FD LST (10 km) Validation</a></li>
                  <li id="GOES-East LST daily animation"><a href="animation.php?sat=GOESR&mode=CONUS&product=LST">CONUS LST daily Animations</a></li>
                  <li id="GOES-East LST validation"><a href="validation.php?sat=GOESR&sensor=ABI&mode=CONUS&product=LST">CONUS LST Validation</a></li>
               </ul>
            </li>
            <li id="GOES-West LST"><a href="index.php?sat=GOESS&product=LST">GOES-West ABI LST</a>
               <ul class="detailContainer">
                  <li id="GOES-West LST daily animation"><a href="animation.php?sat=GOESS&mode=2KMFD&product=LST">FD LST (2 km) daily Animations</a></li>
                  <li id="GOES-West LST validation"><a href="validation.php?sat=GOESS&sensor=ABI&mode=2KMFD&product=LST">FD LST (2 km) Validation</a></li>
                  <li id="GOES-West LST daily animation"><a href="animation.php?sat=GOESS&mode=FD&product=LST">FD LST (10 km) daily Animations</a></li>
                  <li id="GOES-West LST validation"><a href="validation.php?sat=GOESS&sensor=ABI&mode=FD&product=LST">FD LST (10 km) Validation</a></li>
                  <li id="GOES-West LST daily animation"><a href="animation.php?sat=GOESS&mode=CONUS&product=LST">CONUS LST daily Animations</a></li>
                  <li id="GOES-West LST validation"><a href="validation.php?sat=GOESS&sensor=ABI&mode=CONUS&product=LST">CONUS LST Validation</a></li>
               </ul>
            </li>
            <li id="SNPP LST"><a href="https://www.star.nesdis.noaa.gov/jpss/lst.php">SNPP VIIRS LST</a>
               <ul class="detailContainer">
                  <li id="SNPP weekly animation"><a href="animation.php?sat=SNPP&product=LST">SNPP LST Weekly Animations</a></li>
                  <li id="SNPP validation"><a href="validation.php?sat=SNPP&sensor=VIIRS&product=LST">SNPP LST Validation</a></li>
               </ul>
            </li>
            <li id="NOAA-20 LST"><a href="https://www.star.nesdis.noaa.gov/jpss/lst.php">NOAA-20 VIIRS LST</a>
               <ul class="detailContainer">
                  <li id="NOAA-20 weekly animation"><a href="animation.php?sat=JPSS1&product=LST">NOAA-20 LST Weekly Animations</a></li>
                  <li id="NOAA-20 validation"><a href="validation.php?sat=JPSS1&sensor=VIIRS&product=LST">NOAA-20 LST Validation</a></li>
               </ul>
            </li>
         </ul>
      </li>
   </ul>
   <ul>
      <li id="Albedo"><a href="index.php?product=LSA">Albedo</a>
         <ul class="detailContainer">
            <li id="SNPP LSA"><a href="https://www.star.nesdis.noaa.gov/jpss/albedo.php">SNPP VIIRS Albedo</a>
               <ul class="detailContainer">
                  <li id="SNPP weekly animation"><a href="animation.php?sat=SNPP&product=LSA">SNPP Albedo Weekly Animations</a></li>
                  <li id="SNPP validation"><a href="validation.php?sat=SNPP&sensor=VIIRS&product=LSA">SNPP Albedo Validation</a></li>
               </ul>
            </li>
            <li id="NOAA-20 LSA"><a href="https://www.star.nesdis.noaa.gov/jpss/albedo.php">NOAA-20 VIIRS Albedo</a>
               <ul class="detailContainer">
                  <li id="NOAA-20 weekly animation"><a href="animation.php?sat=JPSS1&product=LSA">NOAA-20 Albedo Weekly Animations</a></li>
                  <li id="NOAA-20 validation"><a href="validation.php?sat=JPSS1&sensor=VIIRS&product=LSA">NOAA-20 Albedo Validation</a></li>
               </ul>
            </li>
         </ul>
      </li>
   </ul>
   <ul>
      <li id="Vegetation Index"><a href="index.php?product=VI">Vegetation Index</a>
         <ul class="detailContainer">
            <li id="SNPP Vegetation Index"><a href="https://www.star.nesdis.noaa.gov/jpss/vi.php">SNPP VIIRS Vegetation Index</a>
               <ul class="detailContainer">
                  <li id="SNPP weekly animation"><a href="animation.php?sat=SNPP&product=VI">SNPP Vegetation Index Weekly Animations</a></li>
               </ul>
            </li>
            <li id="NOAA-20 Vegetation Index"><a href="https://www.star.nesdis.noaa.gov/jpss/vi.php">NOAA-20 VIIRS Vegetation Index</a>
               <ul class="detailContainer">
                  <li id="NOAA-20 weekly animation"><a href="animation.php?sat=JPSS1&product=VI">NOAA-20 Vegetation Index Weekly Animations</a></li>
               </ul>
            </li>
         </ul>
      </li>
   </ul>
   <ul>
      <li id="Green Vegetation Fraction"><a href="index.php?product=GVF">Green Vegetation Fraction</a>
         <ul class="detailContainer">
            <li id="SNPP Green Vegetation Fraction"><a href="https://www.star.nesdis.noaa.gov/jpss/gvf.php">SNPP VIIRS Green Vegetation Fraction</a>
               <ul class="detailContainer">
                  <li id="SNPP weekly animation"><a href="animation.php?sat=SNPP&product=GVF">SNPP Green Vegetation Fraction Weekly Animations</a></li>
               </ul>
            </li>
            <li id="NOAA-20 Green Vegetation Fraction"><a href="https://www.star.nesdis.noaa.gov/jpss/vi.php">NOAA-20 VIIRS Green Vegetation Fraction</a>
               <ul class="detailContainer">
                  <li id="NOAA-20 weekly animation"><a href="animation.php?sat=JPSS1&product=GVF">NOAA-20 Green Vegetation Fraction Weekly Animations</a></li>
               </ul>
            </li>
         </ul>
      </li>
   </ul>
</div><!-- end of navlist -->
<div style="margin-top: 2px;">
</div>
<?php
// insert disclaimer language
require('includes/ProductDisclaimer.inc');

?>
<br />
	
