			<div class="leftNav">
			<ul>
				<li id="index"><a href="index.php">Home</a>
					<ul class="detailContainer">
						<li id="news_events"><a 
							href="news_events.php">News &amp; Events</a></li>
						<li id="seminars"><a 
							href="seminars.php">Seminars</a></li>
						<li id="meetings"><a 
							href="meetings.php">Scientific Meetings</a></li>
						<li id="staff_all"><a 
							href="staff_all.php">Staff Directory</a></li>
						<li id="training"><a 
							href="training.php">Training &amp; Education</a></li>
						<li id="careers"><a 
							href="careers.php">Career Opportunities</a></li>
						<li id="star_orgchart"><a 
							href="star_orgchart.php">Organization</a></li>
						<li id="acronyms"><a 
							href="acronyms.php">Acronyms</a></li>
						<li id="sitemap"><a 
							href="sitemap.php">Sitemap</a></li>
						<li id="contact"><a 
							href="contact.php">Contact Us</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li id="products"><a href="products.php">Products</a>
					<ul class="detailContainer">
					<ul class="detailContainer">
						<li id="bestof2006"><a 
							href="bestof2006.php">Best of 2006</a></li>
						<li id="bestof2005"><a 
							href="bestof2005.php">Best of 2005</a></li>
						<li id="prod_climate"><a 
							href="prod_climate.php">Climate</a></li>
						<li id="prod_ecosystems"><a 
							href="prod_ecosystems.php">Ecosystems</a></li>
						<li id="prod_weather_water"><a
							href="prod_weather_water.php">Weather and Water</a></li>
						<li id="prod_comm_tran"><a 
							href="prod_comm_tran.php">Commerce &amp; Transportation</a></li>
						<li id="prod_criticalsupport"><a 
							href="prod_criticalsupport.php">Critical Support for NOAA</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li id="stratplans"><a href="stratplans.php">Future Directions</a>
					<ul class="detailContainer">
						<li id="plan_roadmaps"><a 
							href="plan_roadmaps.php">STAR Road Map</a></li>
						<li id="overview"><a 
							href="overview.php">STAR Values</a></li>
						<li id="plan_milestones"><a 
							href="plan_milestones.php">Supporting NOAA Research Goals</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li id="smcd"><a href="smcd.php">Satellite Meteorology 
					&amp; Climatology</a>
					<ul class="detailContainer">
						<li id="smcdroadmap"><a 
							href="smcdroadmap.php">SMCD Road Map</a></li>
						<li id="smcd_projects"><a
							href="smcd_projects.php">SMCD Projects</a></li>
						<li id="spb_index"><a 
							href="spb_index.php">Sensor Physics Branch</a></li>
						<li id="opdb_index"><a 
							href="opdb_index.php">Operational Products Development Branch</a></li>
						<li id="emb_index"><a 
							href="emb_index.php">Environmental Monitoring Branch</a></li>
						<li id="smcd_pub"><a 
							href="smcd_pub.php">SMCD Publications</a></li>
					</ul>
				</li>
			</ul>
			<ul>
				<li id="socd_index"><a 
					href="socd_index.php">Satellite Oceanography &amp; Climatology</a>
					<ul class="detailContainer">
						<li id="socdr_index"><a 
							href="socdr_index.php">SOCD Road Map</a></li>
						<li id="socd_projects"><a
							href="socd_projects.php">SOCD Projects</a></li>
				    <li id="osb_index"><a 
				    	href="osb_index.php">Ocean 
				     	Sensors Branch</a></li>
						<li id="meb_index"><a 
							href="meb_index.php">Marine Ecosystems Branch</a></li>
						<li id="opb_index"><a 
							href="opb_index.php">Ocean Physics Branch</a></li>
						<li id="socd_pub"><a 
							href="socd_pub.php">SOCD Publications</a></li>
						<li id="cw_index"><a 
							href="http://coastwatch.noaa.gov/cw_index.html">CoastWatch</a></li>
						<li id="coralreefwatch.noaa.gov2"><a 
							href="http://coralreefwatch.noaa.gov/satellite/index.html">Coral Reef Watch</a></li>
					</ul>
				</li>
			</ul>

			<ul>
				<li id="CoRP_index"><a href="CoRP_index.php">Cooperative Research Programs</a>
					<ul class="detailContainer">
						<li id="CoRPRoadmap"><a 
							href="CoRPRoadmap.php">CoRP Road Map</a></li>
						<li id="corp_projects"><a
							href="corp_projects.php">CoRP Projects</a></li>
						<li id="aspb_index"><a 
							href="aspb_index.php">Advanced Satellite Products Branch</a></li>
						<li id="RMMB_index"><a 
							href="RMMB_index.php">Regional and Mesoscale Meteorology Branch</a></li>
						<li id="SCSB_index"><a 
							href="SCSB_index.php">Satellite Climate Studies Branch</a></li>
						<li id="corp_pubs"><a
							href="corp_pubs.php">CoRP Publications</a></li>
						<li id="corp_institutes"><a 
							href="corp_institutes.php">CoRP Institutes &amp; Centers</a></li>
					</ul>
				</li>
			</ul>
			<ul>
				<li id="affiliates"><a href="affiliates.php">Affiliates</a>
					<ul class="detailContainer">
						<li id="www.nnvl.noaa.gov"><a 
							href="http://www.nnvl.noaa.gov/">Environmental Visualization Program</a></li>
						<li id="www.jcsda.noaa.gov"><a 
							href="http://www.jcsda.noaa.gov/">Joint Center for Satellite Data Assimilation (JCSDA)</a></li>
						<li id="cw_index"><a 
							href="http://coastwatch.noaa.gov/cw_index.html">CoastWatch</a></li>
						<li id="coralreefwatch.noaa.gov"><a 
							href="http://coralreefwatch.noaa.gov/satellite/index.html">Coral Reef Watch</a></li>
					</ul>
				</li>
			</ul>
		</div><!-- end of navlist -->

<?php
// insert disclaimer language
require('includes/ProductDisclaimer.inc');

?>

		<div style="margin-top: 2px;">
		<a href="IceSymposiumProgram.php"><img src="images/natice_sym/IDA_logo_perm2.jpg"
		alt="National Ice Center Symposium" /></a>
		</div>
		
		<div style="text-align: center;
		margin-bottom: 20px;
		margin-top: 6px;">
		<a href="http://celebrating200years.noaa.gov/"><img 
		src="images/NOAA200Ann_med.jpg"
		alt="logo for NOAA's 200th Anniversary Celebration website - click to visit site"
		/></a></div>
		
