					<div class="right" style="width: 50%;"><h2 style='text-align: center;'>Other Seminars:<br>
						<a href="seminars.php#upcoming">Upcoming</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
							href="past_seminars_2009.php">2009</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
							href="past_seminars_2008.php">2008</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
							href="past_seminars_2007.php">2007</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
							href="past_seminars_2006.php">2006</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
							href="past_seminars_2006.php#2005pres">2005</a></h2></div>