<?php
$choices_sat = array("GOESR", "GOESS", "GOEST", "GOESU", "SNPP", "JPSS1", "JPSS2", "JPSS3", "JPSS", "HIMAWARI8", "HIMAWARI9", "Applications", "");
$choices_msat = array('G16_G18', 'G16_G19', 'G18_G19');
$choices_mode = array("CONUS", "2KMFD", "FD", "FLDK");
$choices_product = array("LST", "LSA", "SR", "VI", "GVF");
$choices_variable = array("LST", "LSA", "BRF-RGB", "SR", "SR-Land", "TOA-NDVI", "TOC-NDVI", "TOC-EVI", "GVF", "BRF");
#$choices_version = array("v1r4(Operational)", "v2r2");
$choices_network = array("All", "ARM", "NEON", "SURFRAD", "BSRN", "AERONET");
$choices_time = array("day", "night");
$choices_dave = array("3days", "7days");
?>
