<h3 style="text-align:center">Team Members: Yunyue Yu and Heshun Wang</h3>
<br>
<h2> Background </h2>
<p> Surface reflectance (SR) is the most fundamental remotely sensed surface parameter, providing the primary input for most of the higher-level land products which rely on the solar reflective characters, including vegetation indices and leaf area index, land cover, and albedo. Therefore, the quality of SR product is critical to a bunch of downstream products.</p>
<p> The VIIRS SR product is directly heritage from collection 5 MODIS and that it has been validated to stage 1 (Land PEATE adjusted version). The IDPS algorithm has been transitioned to NDE and MODIS algorithm refinements from Collection 6 have been integrated as well.</p>
<p> The JPSS SR products provide directional surface reflectance values for VIIRS 12 bands centered at 0.412 μm, 0.445 μm, 0.488 μm, 0.555 μm, 0.645 μm, 0.672 μm, 0.865 μm (two different spatial resolutions), 1.24 μm, 1.61 μm (two different spatial resolutions), and 2.25 μm.</p> 
<br>
