<link rel="shortcut icon" href="images/favicon.ico">
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="css/main.css">
<script>
<!--// this code tests user screen resolution, and then 
// serves up wider pages for real screens, leaving
// the screen narrower for pathetic 800 x 600 folks.
if (screen.width >= 1024) {
	document.write("<style type='text/css'>table#mainTable { width: 930px; }\n");
	document.write("td.mainPanel { width: 730px; }\n");
	document.write("td.mainPanel#bestOf { width: 910px; }\n");
	document.write("div#topBanner { width: 930px; }\n");
	document.write("</style>");
}
//--> 
</script>
<?php include('/www/star/global/includes/FedAnalytics.inc'); ?>
<META HTTP-EQUIV="expires" VALUE="Thu, 16 Mar 2000 11:00:00 GMT">
<META HTTP-EQUIV="pragma" CONTENT="no-cache">
