<link rel="shortcut icon" href="images/favicon.ico">
<link rel="icon" href="favicon.ico" type="image/x-icon">
<link rel="shortcut icon" href="favicon.ico" type="image/x-icon">
<link rel="stylesheet" href="css/main.css">
<?php
// insert e-mail obfuscator
// use syntax:
// <'questionmark'php Ob("Xiangqian.Wu&#064;noaa.gov"); 'questionmark'>
include('includes/e-mailObfuscator.inc');
include('/www/star/global/includes/FedAnalytics.inc');
?>

