<h3 style="text-align:center">Team Lead: <a href="http://www.star.nesdis.noaa.gov/star/Yu_Y.php" target="_blank">Yunyue (Bob) Yu</a></h3>
<br>
<h2> Land Surface Temperature </h2>
<p> Land surface temperature, a key indicator of the Earth surface energy budget,
is widely required in applications of hydrology, meteorology, and climatology.
It is of fundamental importance to the net radiation budget at the Earth surface
and to monitoring the state of crops and vegetation, as well as an important
indicator of both the greenhouse effect and the energy flux between the
atmosphere and ground (Norman & Becker, 1995; Li & Becker, 1993;).  LST is one
of the land EDRs for both GOES-R and JPSS missions. </p>		 
<br>				
<h2> Surface Albedo  </h2>
<p> Surface Albedo (SURFALB), defined as the ratio between solar radiation reflected by Earth's surface and solar radiation incident at the surface, is a function of both solar illumination and the surface reflective properties. SURFALB is an essential variable linking the earth surface and the climate system. It is a unique property for studying how surface changes affect the energy balance and the overall climate system. </p>
<br>
<h2> Surface Reflectance  </h2>
<p> Surface Reflectance (SR), is defined as the fraction of solar radiation that is reflected by the surface of the Earth, the SR product is an estimate of the surface spectral reflectance after correcting the effects of atmospheric components (gases, aerosols, and thin cirrus clouds). It is a fundamental input parameter for most of the land products which is based on the reflectance characters, for instance, vegetation indices and biophysical variables, surface type, surface albedo. </p>
<br>				
<h2> Vegetation Index and Green Vegetation Fraction </h2>
<p> Vegetation Index (VI) is a spectral transformation of two or more bands designed to enhance the
contribution of vegetation properties and allow reliable spatial and temporal inter- comparisons
of terrestrial photosynthetic activity and canopy structural variations, monitor and characterize
terrestrial landscapes.  VI is related to absorption of photosynthetically active radiation by
vegetation and correlate with biomass or primary productivity. It is a robust empirical measure of
vegetation activity at the land surface and has been widely used to study the spatial and temporal
pattern of vegetation conditions at large scale with the objective to understand the role of
terrestrial vegetation in regional and global processes, such as global carbon and nitrogen cycle,
global hydrological cycle and global energy cycle. </p>
<p> Green Vegetation Fraction(GVF) corresponds to the fraction of ground covered by green
vegetation; it quantifies the spatial extent of the vegetation. GVF is a very good candidate for the
replacement of classical vegetation indices for the monitoring of ecosystems. It is needed for
land surface initialization in numerical weather prediction models and land surface monitoring as
well. </p>
<br>
