			<div class="toolBarContainer">
			<div class="toolBarInner" id="shortVersion">
			<div class="left"></div>

			<div class="right"><a href="index.php">Home</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="sitemap.php">Sitemap</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="contact.php">Contact Us</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="careers.php">Careers</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="https://www.star.nesdis.noaa.gov/intranet/index.php">Intranet</a></div>
		  <div class="clearing"></div>
			<?php require('includes/noScriptWarning.inc'); ?>
  	  </div></div>
<table id="mainTable" cellpadding="0" cellspacing="0" border="0"
	summary="this table is for page layout purposes only, not tabular data">    
