			<div class="toolBarContainer">
			<div class="toolBarInner">
			<div class="left"><a href="index.php">Home</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="sitemap.php">Sitemap</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="contact.php">Contact Us</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="careers.php">Careers</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="https://www.star.nesdis.noaa.gov/intranet/index.php">Intranet</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a 
				href="http://usasearch.gov/search?v:project=firstgov&amp;form=advanced-firstgov&amp;v:frame=form&amp;affiliate=star.nesdis.noaa.gov_star">Advanced
	    	Search</a></div>

			<div class="right"><form id="smallSearch"
				method="get" action="http://usasearch.gov/search"><input 
		  	type="hidden" name="affiliate" value="star.nesdis.noaa.gov_star" /><input 
		  	type="hidden" name="v:project" value="firstgov" /><input 
		  	title="Enter your search terms here."
		  	type="text" name="query" style="width: 11em; color: #666;" 
		  	id="query-field"
		  	value="Enter search term(s)"
				onfocus="if(this.value=='Enter search term(s)')this.value='';"
		  	/> <input 
		  	type="submit" value="Search" /></form></div>
		  <div class="clearing"></div>
			<?php require('includes/noScriptWarning.inc'); ?>
  	  </div></div>

<table id="mainTable" cellpadding="0" cellspacing="0" border="0"
	summary="this table is for page layout purposes only, not tabular data">
    
