<h3 style="text-align:center">Team Members: Yunyue Yu, Corinne Carter, and Zhangyan Jiang</h3>
<br>
<h2> Background </h2>
<p> Vegetation Index (VI) is a spectral transformation of two or more bands designed to enhance the
contribution of vegetation properties and allow reliable spatial and temporal inter- comparisons
of terrestrial photosynthetic activity and canopy structural variations, monitor and characterize
terrestrial landscapes.  VI is related to absorption of photosynthetically active radiation by
vegetation and correlate with biomass or primary productivity. It is a robust empirical measure of
vegetation activity at the land surface and has been widely used to study the spatial and temporal
pattern of vegetation conditions at large scale with the objective to understand the role of
terrestrial vegetation in regional and global processes, such as global carbon and nitrogen cycle,
global hydrological cycle and global energy cycle. </p>
<br>

<h2> Data access </h2>
<p> The data are available to the public via NOAA <a href="https://www.avl.class.noaa.gov/saa/products/search?sub_id=0&datatype_family=JPSS_NGRN&submit.x=28&submit.y=8" target="_blank">CLASS</a>, and please refer to the <a href="others/documents/instructions_vi_gvf_dat_from_CLASS.pdf" target="_blank">instruction</a> for details on how to order and download the data . </p>
<br>
