<h3 style="text-align:center">Team Members: Yunyue Yu, Jingjing Peng, and Heshun Wang</h3>
<br>
            <h2 align="center"> VIIRS Surface Albedo EDR </h2>
            <br>
            <h2 align="left"> Description </h2>
            <p> Surface Albedo (SURFALB), defined as the ratio between solar radiation reflected by Earth's surface and solar radiation incident at the surface, is a function of both solar illumination and the surface reflective properties. SURFALB is an essential variable linking the earth surface and the climate system. It is a unique property for studying how surface changes affect the energy balance and the overall climate system. </p>
            <br>
            <h2 align="left"> Known Issues of VIIRS Surface Albedo EDR</h2>
            <ul style="list-style-type:disc;"; class="tighter"> <b>
               <li>A horizontal strip is observed in Greenland area due to the climatology discontinuity which happens under cloudy conditions </li>
               <li> Strong spatial discontinuity is observed in the Antarctic region due to 1) the misuse of desert LUT for snow surface when the snow is not detected by upstream snow cover EDR; 2) the uncertainty in snow albedo LUT at different solar/view angles; 3) difference between clear-sky direct retrieval and cloudy filled retrieval using climatology </li>
               <li> Data gap is observed in the Arctic Ocean due to a missing of climatology over two tiles during delivery from ASSISTT to NDE </li>
               <li> Spatial coverage of sea-ice albedo varies from day to day following the upstream ice concentration dataset </li>
            </b> </ul>
            <p> All these issues will be eliminated in the next operational version. </p>
            <p> For more detail about this EDR, please visit <a href="https://www.star.nesdis.noaa.gov/jpss/albedo.php" target="_blank"> JPSS Albedo EDR</a>. </p>
            <br>
            <br>
